[template]
keys        = [ "/lb" ]
owner       = "nginx"
mode        = "0644"
src         = "nginx.conf.tmpl"
dest        = "/etc/nginx/nginx.conf"
check_cmd   = "/usr/sbin/nginx -t -c {{.src}}"
reload_cmd  = "/usr/sbin/nginx -s reload"
